spring.application.name=nw-trails-backend
server.port=8080

app.security.jwt.secret=NWTrailsPhase3JwtSecretKeyForGroup06BackendOnly
app.security.jwt.access-token-seconds=3600
app.security.jwt.refresh-token-seconds=1209600

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.data.mongodb.uri=mongodb://localhost:27017/nw_trails
